rootProject.name = 'rim-tool'

includeBuild('hirs') {
    dependencySubstitution {
        substitute(module('org.hirs:HIRS_Utils')).using(project(':HIRS_Utils'))
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("gradle/versions.toml"))
        }
    }
   repositories {
        flatDir { dirs "lib" }
        maven { url = uri("https://maven-central.storage-download.googleapis.com/maven2") } // default to google mirror
        maven { url = uri("https://packages.atlassian.com/mvn/maven-atlassian-external/") } // fallback to atlassian mirror
        mavenCentral() // Fallback to maven
        gradlePluginPortal()  // default gradle plugin repo 
    }
}
